### ISSUE TITLE
佬什么时候出个英文版本

### ISSUE THREAD

**Issue by Dzy0726** [fky2015/resume-ng#10]

**Comment by fky2015** [comment]
其实这段时间一直有这个打算，我这段时间抽时间搞一下。也欢迎你提供一些建议！

**Comment by Dzy0726** [comment]
直接按现在的版本英文化就已经吊打很多模版了哈哈哈  期待开发新功能和特点~

**Comment by ppdogg** [comment]
overleaf有类似的英文模板，我就是因为喜欢英文模板的风格找的这种中文模板
