### ISSUE TITLE
模板太棒了 血书求一英文版本！

### ISSUE THREAD

**Issue by jiejie567** [fky2015/resume-ng#11]

**Comment by fky2015** [comment]
在 https://github.com/fky2015/resume-ng/tree/english 分支已经提供了一个英文版本，欢迎尝鲜并提出建议 :smile: 

Readme 还是中文的没有修改，不过可以在 main.pdf 预览到效果。

**Comment by jiejie567** [comment]
感谢，已经用上了。要是添加图片，整体能不下移就更好了。另外，每个栏目里我觉得都加个item可能级别会更清晰。总之，万分感谢！
